name: Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: [8.3]
                laravel: [11.*]

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
                  coverage: none

            - name: Install Composer dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                  composer update --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/pest
